# Generated by Django 5.0.6 on 2025-09-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_remove_student_id_remove_student_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stud_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='cls',
            field=models.CharField(default=0.0, max_length=50),
            preserve_default=False,
        ),
    ]
