# Generated by Django 5.0.6 on 2025-09-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_stud_login_student_cls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cls',
            new_name='clas',
        ),
    ]
