# Generated by Django 5.0.6 on 2025-09-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0004_rename_cls_student_clas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
