# Generated by Django 5.0.6 on 2025-09-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0005_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('clas', models.CharField(max_length=50)),
            ],
        ),
    ]
