# Generated by Django 5.0.6 on 2025-09-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0009_mentor_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor_login',
            name='department',
        ),
        migrations.RemoveField(
            model_name='mentor_login',
            name='name',
        ),
    ]
