# Generated by Django 5.0.6 on 2025-09-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0010_remove_mentor_login_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor_login',
            name='name',
            field=models.CharField(default='', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
