# Generated by Django 5.0.6 on 2025-09-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0011_mentor_login_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentor_Login',
            new_name='Men_Login',
        ),
    ]
