# Generated by Django 5.0.6 on 2025-09-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0012_rename_mentor_login_men_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Men_Login',
            new_name='Mentor_Login',
        ),
    ]
