# Generated by Django 5.0.6 on 2025-09-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0013_rename_men_login_mentor_login'),
    ]

    operations = [
    ]
