# Generated by Django 5.0.6 on 2025-09-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0014_add_name_to_mentor_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor_login',
            name='name',
        ),
    ]
