# Generated by Django 5.0.6 on 2025-09-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0016_mentor_login_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor_Login',
        ),
    ]
