# Generated by Django 5.0.6 on 2025-09-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0017_delete_mentor_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=80)),
            ],
        ),
    ]
