# Generated by Django 5.0.6 on 2025-09-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0018_mentor_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
