# Generated by Django 5.0.6 on 2025-09-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0021_delete_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('primary_domain', models.CharField(max_length=80)),
                ('experience', models.IntegerField()),
                ('alternative_domains', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
