# Generated by Django 5.0.6 on 2025-09-21 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0022_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocate_Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_domain', models.CharField(max_length=50)),
                ('mentor_domain', models.CharField(max_length=50)),
                ('mentor_alt_domains', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='allocation.mentor')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.team')),
            ],
        ),
    ]
