# Generated by Django 5.0.6 on 2025-09-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0026_delete_allocate_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocate_Mentor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_domain', models.CharField(max_length=50)),
                ('mentor_domain', models.CharField(blank=True, max_length=50, null=True)),
                ('mentor_alt_domains', models.TextField(blank=True, null=True)),
                ('mentor_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
