# Generated by Django 5.0.6 on 2025-10-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0027_allocate_mentor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
