# Generated by Django 5.0.6 on 2025-10-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0029_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_domain', models.CharField(max_length=100)),
                ('mentor_name', models.CharField(max_length=100)),
                ('mentor_domain', models.CharField(max_length=100)),
                ('alt_domains', models.TextField(blank=True)),
                ('experience', models.CharField(max_length=50)),
                ('similarity_score', models.FloatField()),
                ('reason', models.TextField(blank=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
