# Generated by Django 5.0.6 on 2025-10-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0030_allocationresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
