# Generated by Django 5.0.6 on 2025-10-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0032_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('student_class', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=100)),
                ('members', models.CharField(max_length=300)),
                ('member_names', models.CharField(max_length=300)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModifyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('student_class', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=100)),
                ('members', models.CharField(max_length=300)),
                ('member_names', models.CharField(max_length=300)),
                ('new_project_title', models.CharField(blank=True, max_length=200, null=True)),
                ('new_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('new_members', models.CharField(blank=True, max_length=300, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
