# Generated by Django 5.0.6 on 2025-10-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0033_approvedteam_modifyrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModifyRequest',
        ),
    ]
