# Generated by Django 5.0.6 on 2025-12-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0038_zerothreviewremark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZerothReviewRemark',
        ),
    ]
