# Generated by Django 5.0.6 on 2025-12-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0039_delete_zerothreviewremark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZerothReviewRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('mentor_name', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=200)),
                ('remark', models.TextField()),
                ('color', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('team_name', 'mentor_name', 'heading', 'remark', 'color')},
            },
        ),
    ]
