# Generated by Django 5.0.6 on 2025-12-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0043_delete_zerothreviewremark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZerothReviewRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('mentor_name', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('remark', models.TextField()),
                ('color', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='zerothreviewremark',
            constraint=models.UniqueConstraint(fields=('team_name', 'mentor_name', 'heading'), name='unique_zeroth_review_remark'),
        ),
    ]
