# Generated by Django 5.0.6 on 2025-12-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0044_zerothreviewremark_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZerothReviewRemark',
        ),
    ]
