# Generated by Django 5.0.6 on 2025-12-25 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0046_zerothreviewremark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('ann_type', models.CharField(choices=[('deadline', 'Deadline'), ('schedule', 'Schedule'), ('instruction', 'Instruction')], max_length=20)),
                ('target_role', models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('both', 'Student & Mentor')], max_length=20)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('deadline_time', models.TimeField(blank=True, null=True)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('schedule_time', models.CharField(blank=True, max_length=50, null=True)),
                ('venue', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_list', to='allocation.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-seen_at'],
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
