# Generated by Django 5.0.6 on 2025-12-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0047_announcement_announcementstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementstatus',
            name='announcement',
        ),
        migrations.AlterUniqueTogether(
            name='announcementstatus',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='announcementstatus',
            name='user',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='AnnouncementStatus',
        ),
    ]
