# Generated by Django 5.0.6 on 2025-12-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0049_announcement_announcementstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnouncementStatus',
        ),
    ]
