# Generated by Django 5.0.6 on 2025-12-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0051_announcementstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementstatus',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='announcementstatus',
            name='user',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='AnnouncementStatus',
        ),
    ]
