# Generated by Django 5.0.6 on 2025-12-26 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0055_remove_announcementstatus_announcement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('ann_type', models.CharField(choices=[('deadline', 'Deadline'), ('schedule', 'Schedule'), ('instruction', 'Instruction')], max_length=20)),
                ('target_role', models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('both', 'Both')], max_length=20)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('deadline_time', models.TimeField(blank=True, null=True)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by_username', models.CharField(max_length=80)),
                ('created_by_name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_role', models.CharField(max_length=20)),
                ('receiver_id', models.CharField(max_length=80)),
                ('receiver_name', models.CharField(max_length=80)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.announcement')),
            ],
        ),
    ]
