# Generated by Django 5.0.6 on 2026-01-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0056_announcement_announcementstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('review_stage', models.CharField(help_text='zeroth / first / second / third', max_length=50)),
                ('doc_type', models.CharField(choices=[('abstract', 'Abstract PDF'), ('report', 'Final Report PDF'), ('ppt', 'Presentation PPT')], max_length=20)),
                ('file_url', models.URLField(max_length=500)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
