# Generated by Django 5.0.6 on 2026-01-21 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0057_projectdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(max_length=20)),
                ('file_type', models.CharField(max_length=20)),
                ('cloudinary_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.team')),
            ],
        ),
    ]
