# Generated by Django 5.0.6 on 2026-01-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0060_projectfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectFile',
        ),
    ]
