# Generated by Django 5.0.6 on 2026-01-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0061_delete_projectfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('review_type', models.CharField(max_length=20)),
                ('file_type', models.CharField(max_length=20)),
                ('cloudinary_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
