# Generated by Django 5.0.6 on 2026-02-24 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0062_projectfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZerothReviewRemark',
        ),
    ]
