# Generated by Django 5.0.6 on 2026-02-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0063_delete_zerothreviewremark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZerothReviewRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('mentor_name', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('remark', models.TextField()),
                ('color', models.CharField(max_length=20)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('ppt', 'PPT'), ('abstract', 'Abstract')], default='pdf', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='zerothreviewremark',
            constraint=models.UniqueConstraint(fields=('team_name', 'mentor_name', 'heading', 'file_type'), name='unique_zeroth_review_remark'),
        ),
    ]
