# Generated by Django 5.0.6 on 2026-02-24 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0064_zerothreviewremark_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZerothReviewRemark',
        ),
    ]
