# Generated by Django 5.0.6 on 2026-03-14 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0068_delete_projectremarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('review_type', models.CharField(max_length=20)),
                ('file_type', models.CharField(max_length=20)),
                ('mentor_name', models.CharField(max_length=100)),
                ('cloudinary_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allocation.projectfile')),
            ],
            options={
                'db_table': 'project_remarks',
                'ordering': ['-created_at'],
            },
        ),
    ]
