# Generated by Django 5.0.6 on 2026-03-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0069_projectremarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectRemarks',
        ),
    ]
