# Generated by Django 5.0.6 on 2026-03-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0071_projectremarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstReviewRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('mentor_name', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('remark', models.TextField()),
                ('color', models.CharField(max_length=20)),
                ('file_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'first_review_remarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecondReviewRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('mentor_name', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('remark', models.TextField()),
                ('color', models.CharField(max_length=20)),
                ('file_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'second_review_remarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThirdReviewRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('mentor_name', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('remark', models.TextField()),
                ('color', models.CharField(max_length=20)),
                ('file_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'third_review_remarks',
                'ordering': ['-created_at'],
            },
        ),
    ]
