# Generated by Django 5.0.6 on 2026-03-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0072_firstreviewremark_secondreviewremark_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstReviewRemark',
        ),
        migrations.DeleteModel(
            name='SecondReviewRemark',
        ),
        migrations.DeleteModel(
            name='ThirdReviewRemark',
        ),
    ]
